# numpy 学习笔记


## numpy 基础

1. numpy 初始化常用 array 函数
   - array 可传入一个数组


In [ ]:
import numpy as np

a= np.array([1, 2, 3, 4, 5])

print(a)
print(a.shape)
print(a.dtype)

print("------")
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print(a.dtype)

- zeros 初始化一个全零的数组，只需传入数组的形状即可
- ones 初始化为一个全 1 的数组，只需传入数组的形状即可
- empty 初始化一个空数组，不是全零
- eye 初始化为一个 n 阶单位矩阵


In [ ]:
import numpy as np
b = np.zeros((3,4))
c = np.ones((2,3),dtype=np.int16)
d = np.empty((2,3))
e =np.eye(4)
print(b)
print("------")
print(c)
print("------")
print(d)
print("------")
print(e)

2. arange 是 Python 内置函数 range 的数组版：


In [ ]:
import numpy as np
a = np.arange(10,20,2) // 10-20 步长为2
a

3. ndarray 的数据类型
   - dtype 可显示数组的数据类型
   - astype 可以将数据类型进行转换
   - 如果字符串数组存储的是数据字符串，用 astype 转换可以变成对应数据


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print("------")
print(float_arr.dtype)
print(float_arr)
print("------")
a = np.array(['1.25', '-9.6', '42'])
b = a.astype(float)
print(b)


## 广播规则

广播规则的核心思想是：

维度对齐：如果两个数组的维度数不同，则在维度数较小的数组前面添加维度，使其维度数与另一个数组相同。

形状匹配：如果两个数组在某个维度上的大小相同，或者其中一个数组在该维度上的大小为 1，则它们在该维度上是兼容的。

运算执行：对于兼容的维度，NumPy 会将大小为 1 的数组“广播”到与另一个数组相同的形状，然后进行运算。

In [112]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # 形状为 (2, 3)
arr2 = np.array([10, 20, 30])  # 形状为 (3,)

print(arr1 + arr2)

[[11 22 33]
 [14 25 36]]


## numpy 数组运算

1. 数组与标量的算术运算（加减乘除运算）会应用到 numpy 数组的每个值
2. 大小相同的数组之间的比较会生成布尔值数组


In [ ]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print("------")
b = arr * arr
print(b)
print("------")
c = arr - arr
print(c)
print("------")
d = 1 / arr
print(d)
print("------")
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
e = arr2 > arr
print(e)

## 切片和索引

1. numpy 的索引和切片和 python 类似
2. 对切片的操作也会应用到原数组


In [ ]:
import numpy as np
arr = np.arange(10)
arr_slice = arr[5:8]

print(arr_slice)
print("------")
arr_slice[1] = 66 #切片的索引1是原数组索引6
print(arr)


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print("------")
print(arr[2,1])
print("------")
print(arr[2][1]) #二者等价

In [ ]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d.shape)
print("------")
print(arr3d[1]) #如果对高维数组进行索引，返回的对象是一个低维数组
print(arr3d[1].shape) #此处是对第一个维度进行索引，返回的是一个二维数组

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print("------")
print(arr[:2]) #对第一个维度进行切片
print("------")
print(arr[1:]) #对第二个维度进行切片
print("------")
arr[:2, 1:]

3. 布尔索引
   * 布尔型数组可用于数据索引


In [ ]:
import numpy as np 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]]) 
print  ('大于 5 的元素是：' ) 
print (x[x >  5])

4. 改变数组形状


In [ ]:
import numpy as np 
b = np.zeros(shape=(3,4))
#使用shape改变数组的形状
b.shape=(4,3)
print(b)

#或者也可以使用reshape方法
b = b.reshape(2,2,3)#改变为三维
print("------")
print(b)

## 数组迭代
* 可以用嵌套循环进行遍历，但高维时比较麻烦
* 使用np.nditer()函数可以更简便遍历

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# 使用嵌套循环
for row in arr:
    for element in row:
        print(element)

# 使用 np.nditer()
for element in np.nditer(arr):
    print(element)

## 数组操作

1. 数组转置和轴对换
   - 使用 T 属性或者 transpose 方法获得矩阵转置


In [ ]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
print(arr)
print("------")
print(arr.T)
print("------")
print(arr.transpose())

- 计算矩阵内积


In [ ]:
import numpy as np
arr = np.random.randn(6, 3)
print(arr)
print("------")
print(np.dot(arr.T, arr))

- 如果使用 transpose 进行转置计算内积，在转置时要存入一个变化后的轴编号


In [ ]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print("------")
print(arr.transpose((1, 0, 2)))


## 通用函数：快速的元素级数组函数


### 一元函数

- abs,fabs:计算绝对值，fabs 计算非复数更快
- sqrt:各元素的平方根
- square:各元素平方
- exp:各元素的指数
- log，log10,log2,log1p:分别是 ln，lg，log2，log(1+x)
- sign:各元素的正负号（正数为+1，负数为-1，零为 0）
- #ceil,floor:向上向下去整
- rint:四舍五入
- isnan:返回哪些是"NaN"的布尔数组
- cos,cosh,sin,sinh,tan,tanh,arccos,arcsin,arctan:三角函数


In [ ]:
import numpy as np
arr = np.arange(1,10)
print(arr)
print("------")
print(np.abs(arr))
print("------")
print(np.sqrt(arr))
print("------")
print(np.square(arr))
print("------")
print(np.exp(arr))
print("------")
print(np.log(arr))




In [ ]:
import numpy as np
arr = np.arange(1,10)
print("------")
print(np.sign(arr))
print("------")
print(np.ceil(arr))
print("------")
print(np.floor(arr))
print("------")
print(np.rint(arr))
print("------")
print(np.sin(arr))

### 二元函数

- add：对应元素相加
- subtract:前减后
- multiply:乘法（不是点积，而是对应位置元素相乘，要求形状相同或者符合广播）
- divide,floor_divide:除法，向下除法（都会丢弃余数，只保留整数）
- power:前为 A，后为 B，计算 A^B
- maximum,fmax:相同位置元素求最大值，fmax 会忽略 NaN
- minimum,fmin:相同位置元素求最小值，fmin 会忽略 NaN
- mod:求模运算（取余）
- greater，greater_equal...:比较预算
- logic_and,logic_or,logic_xor：& | ^


In [ ]:
import numpy as np
arr1 = np.random.randn(10)
arr2 = np.arange(1,11)
print(np.add(arr1, arr2))
print("------")
print(np.subtract(arr1, arr2))
print("------")
print(np.multiply(arr1, arr2))
print("------")
print(np.divide(arr1, arr2))
print("------")
print(np.power(arr1, arr2))

In [ ]:
import numpy as np
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
print("------")
print(np.maximum(arr1, arr2))
print("------")
print(np.minimum(arr1, arr2))
print("------")
print(np.mod(arr1, arr2))



## 条件逻辑用于数组运算

- numpy.where 函数是三元表达式 x if condition else y 的矢量化版本。
- np.where 的第二个和第三个参数不必是数组，它们都可以是标量值。


In [ ]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

result = np.where(cond, xarr, yarr)

print(result)

print("------")
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

## 数学统计方法

- sum:对全部或轴向元素求和
- mean:求算数平均数
- std,var:标准差和方差
- min,max:求最小最大值
- argmin,argmax:最小最大值的索引


In [ ]:
import numpy as np
arr = np.random.randn(5, 4)
print(arr.mean())
print("------")
print(np.mean(arr))#两者等价，其他函数均成立
print("------")
print(arr.sum())
print("------")
print(arr.std())
print("------")
print(np.var(arr))

- mean 和 sum 这类的函数可以接受一个 axis 选项参数，用于计算该轴向上的统计值


In [ ]:
import numpy as np
arr = np.random.randn(5, 4)
print(arr.mean(axis=1))
print("------")
print(arr.sum(axis=0))
#arr.mean(1)是“计算行的平均值”，arr.sum(0)是“计算每列的和”。

- 对于布尔型数组，sum 可以求出一共有多少个 True
- any()可以判断是否有 1 个以上的 True
- all()判断是否全是 True

In [ ]:
import numpy as np
arr = np.random.randn(10)
print(arr)
print("------")
print(arr > 0) #对numpy数组进行布尔操作，返回一个布尔值数组
print("------")
print((arr > 0).sum())#对布尔值数组进行求和操作，True会被强制转换为1
print("------")
print((arr > 0).any())#检查数组中是否存在True
print("------")
print((arr > 0).all())#检查数组中是否全为True

## 排序

- 跟 Python 内置的列表类型一样，NumPy 数组也可以通过 sort 方法就地排序：


In [ ]:
import numpy as np
arr = np.random.randn(6)
print(arr)
print("------")
arr.sort()
print(arr)

- 多维数组可以在任何一个轴向上进行排序，只需将轴编号传给 sort 即可：
- np.sort 返回的是数组的已排序副本


In [ ]:
arr = np.random.randn(4, 3)
print(arr)
print("------")
arr.sort(0) #沿着行的方向进行排序，也就是对列排序
print(arr)
print("------")
print(np.sort(arr,axis=1))#沿着列的方向进行排序，也就是对行排序
print("------")


In [ ]:
import numpy as np
arr = np.random.randn(10)
#对排好序的数组进行切片操作，可以得到指定大小的数组
print(arr[int(0.05 * len(arr))]) #求5%分位数

## 数组的集合运算

- unique(x):计算 x 中的唯一元素，并返回排序结果
- intersect1d(x,y):计算 x 和 y 中的公共元素并返回有序结果
- union1d(x,y):计算 x 和 y 的并集，并返回有序结果
- isin(x,y):得到一个表示 x 的元素是否存在于 y 中的布尔型数组
- setdiff1d(x,y):集合的差：元素在 x 而不在 y 中
- setxor1d(x,y):存在于一个数组但不同时存在于两个数组的元素


In [ ]:
import numpy as np;
arr1 = np.array([5, 0, 1, 3, 2])
arr2 = np.array([1, 2, 3, 4, 5])
print(np.unique(arr1))
print("------")
print(np.intersect1d(arr1, arr2))
print("------")
print(np.union1d(arr1, arr2))
print("------")
print(np.isin(arr1, arr2))
print("------")
print(np.setdiff1d(arr1, arr2))
print("------")
print(np.setxor1d(arr1, arr2))

## numpy文件输入输出
* save函数将numpy数组保存为npy文件
* load函数将npy文件加载为数组

In [ ]:
import numpy as np
arr = np.arange(10)
np.save('some_array.npy', arr)

print(np.load('some_array.npy'))

* savez函数将多个数组保存到npz文件中
* load函数加载npz时，得到字典对象，通过索引进行访问

In [ ]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.random.randn(10)
#np.savez('array_archive.npz', a=arr1, c=arr2)
arch = np.load('array_archive.npz')
print(arch['c'])

## 线性代数
* 矩阵乘法dot函数

In [ ]:
import numpy as np
x= np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(x.dot(y))
print("------")
print(np.dot(x,y))

print("------")
a = x @ np.ones(3) # at也可以进行矩阵乘法
print(a)

### numpy.linalg中的矩阵运算函数
* diag:以一维数组返回方阵对角线元素，或者将一维数组转换为方阵，非对角为0
* dot:矩阵乘法
* trace:求对角线元素的和
* det:求行列式
* eig：求本征值和本征向量
* inv:求矩阵的逆
* qr:求矩阵的qr分解
* svd:计算矩阵的奇异值分解
* solve：解线性方程组Ax=b，A为方阵
* lstsq:求Ax=b的最小二乘解

In [ ]:
import numpy as np
import numpy.linalg as LA

X = np.random.randn(5, 5)
print(np.diag(X))
print("------")
mat = X.T.dot(X)
print(mat)
print("------")
print(LA.trace(X))
print("------")
print(LA.det(X))
print("------")
print(LA.inv(X))
print("------")
q, r = LA.qr(mat)
print(f"q:{q}")
print(f"r:{r}")


## numpy random下的函数
* seed:确定随机数生成器的种子
* permutation：返回一个序列的随机排列或者随机排列范围
* shuffle:对序列仅随机排序
* rand:产生均匀分布的样本值
* randint:从给定的上下限范围内随机取整数
* randn:产生正态分布（均值为1，标准差为1）的样本值
* binomial:产生二项分布的样本值
* normal:产生正态分布的样本值
* beta:产生beta分布样本值
* chisquare:产生卡方分布的样本值
* gamma:产生Gamma分别样本值
* uniform:产生[0,1)中均匀分布的样本值

In [ ]:
import numpy as np

np.random.seed(0)  # 设置种子为 0 这是全局的随机数生成器
print(np.random.rand(5))  # 每次运行结果相同
print("------")
rng = np.random.RandomState(1234)  # 创建一个随机数生成器，隔离的随机数生成器
print(rng.rand(6))  # 生成随机数
print("------")
arr = np.arange(10)
print(np.random.permutation(arr))  # 随机排列数组
print("------")
np.random.shuffle(arr)  # 对数组进行随机排序，原地操作，不会返回新数组
print(arr)

In [111]:
import numpy as np
a = np.random.rand(5)  # 生成一个 5*5 的随机数组
print(a)
print("------")
b = np.random.randint(1, 10, 5) # 从 [1, 10) 中随机取 5 个整数
print(b)
print("------")
c = np.random.randint(0, 5, (2, 3))  # 从 [0, 5) 中随机取 2x3 的整数数组 形状未指定则返回单个样本值
print(c)
c = np.random.randint(0, 5, 2) 
print(c)
print("------")
d = np.random.randn(5)  # 生成一个 5 个标准正态分布的随机数组
print(d)
print("------")
print(np.random.binomial(10, 0.5, (2,3))) # 10次试验，每次成功概率0.5, 产生 2x3 的样本值数组 形状未指定则返回单个样本值，每个值表示实验的期望
print(np.random.binomial(100, 0.1))


[0.0355818  0.38816908 0.55567904 0.35643989 0.63171853]
------
[3 9 9 7 5]
------
[[1 0 4]
 [3 3 4]]
[2 3]
------
[-0.11734316 -0.03502282  0.65449199  0.24056433  0.41709786]
------
[[4 3 4]
 [9 5 9]]
11


In [ ]:
import numpy as np

print(np.random.normal(5, 2, (2, 3)))  # 均值为 5，标准差为 2，产生 2x3 的样本值数组 形状未指定则返回单个样本值
print("------")
print(np.random.beta(1, 5, 10)) #参数a=1,b=5,生成10个样本
print("------")
print(np.random.chisquare(2, 10)) #自由度为2，生成10个样本
print("------")
print(np.random.gamma(5, 1, 10)) #形状参数为5，尺度参数为1，生成10个样本
print("------")
print(np.random.uniform(0, 1, 5))  # 产生 5 个 [0, 1) 之间的均匀分布样本值
print(np.random.uniform(-1, 1, (2, 3)))  # 产生 2x3 的 [-1, 1) 之间的均匀分布样本值数组